[package]
name = "RustAdapterProcess"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libloading = "0.7.3"
thunder_rs = { path = "../../" }
byteorder = "1.4.3"